apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-outbound
spec:
  ports:
  - name: "25826"
    port: 25826
    targetPort: 25826
metadata:
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: logstash
  name: logstash-inbound
spec:
  type: LoadBalancer
  ports:
  - name: "5044"
    port: 5044
    targetPort: 5044
  selector:
    app: logstash
status:
  loadBalancer: {}
